version: "3.3"
services:
  app:
    container_name: kyc-server
    image: kyc-server
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 0.0.0.0:3001:3001
    env_file:
      - .env
