# GD3YZRV4WMPZG5JIX5HLNLERB4DRFT6WBNLGEJ2NKLUCR6IKFE34CUUH
seed_phrase = "omit layer beauty bracket film basket achieve car lyrics ladder oblige frame frost pill oxygen agent industry admit wide deer horse dwarf kick august"